//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:/df.
        /// </summary>
        internal static string defaultFolder {
            get {
                return ResourceManager.GetString("defaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:/dest1.
        /// </summary>
        internal static string destination1 {
            get {
                return ResourceManager.GetString("destination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:/dest2.
        /// </summary>
        internal static string destination2 {
            get {
                return ResourceManager.GetString("destination2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:/test1.
        /// </summary>
        internal static string folder1 {
            get {
                return ResourceManager.GetString("folder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:/test2.
        /// </summary>
        internal static string folder2 {
            get {
                return ResourceManager.GetString("folder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w+.txt.
        /// </summary>
        internal static string pattern1 {
            get {
                return ResourceManager.GetString("pattern1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w+.doc.
        /// </summary>
        internal static string pattern2 {
            get {
                return ResourceManager.GetString("pattern2", resourceCulture);
            }
        }
    }
}
